<?php
$session = new \SlimSession\Helper;
?>

<html>
  <head>
    <title>WebIntern - Want to join us?</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" type="text/css" href="
    <?php
      echo '//'.$_SERVER['HTTP_HOST'].'/internship/front-pages.css';
    ?>
    ">
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">WebIntern</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="
            <?php
              echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php';
            ?>
            ">Sign in</a>
            <a class="mdl-navigation__link" href="
            <?php
              echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php/regis';
            ?>
            ">Join us</a>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title-drawer">WebIntern</span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="
          <?php
            echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php';
          ?>
          ">Sign in</a>
          <a class="mdl-navigation__link" href="
          <?php
            echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php/regis';
          ?>
          ">Join us</a>
        </nav>
      </div>

      <div class="main">
        <h3 class="header">Want to join us?</h3>

        <form class="form" id="regis-form" enctype="multipart/form-data" target="upload_target">
          <i class="material-icons">
          person
          </i>
          <div class="required mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="text" id="user_name" name="user_name">
            <label class="mdl-textfield__label" for="user_name">Username (Your unique identity) <a>*</a></label>
            <span class="mdl-textfield__error">Please fill out this field.</span>
          </div>

          <br><br>

          <i class="material-icons">
          enhanced_encryption
          </i>
          <div class="required mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="password" id="password" name="password">
            <label class="mdl-textfield__label" for="password">Password (Your security key) <a>*</a></label>
            <span class="mdl-textfield__error">Please fill out this field.</span>
          </div>
        
          <br><br>

          <i class="material-icons">
          enhanced_encryption
          </i>
          <div class="required mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="password" id="password_confirm" name="password_confirm">
            <label class="mdl-textfield__label" for="password_confirm">Confirm Password (Make sure) <a>*</a></label>
            <span class="mdl-textfield__error">Please fill out this field.</span>
          </div>
        
          <br><br>
          <i class="material-icons">
          mail
          </i>
          <div class="required mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="text" id="email" name="email">
            <label class="mdl-textfield__label" for="email">Email (Your unique contact source) <a>*</a></label>
            <span class="mdl-textfield__error">Please fill out this field in correct format.</span>
          </div>
        
          <br><br>

          <div>
          <i class="material-icons">
          add_a_photo
          </i>
            <b class="upload_label">Profile Image : </b>
            <input type="file" accept="image/*" id="image_upload" name="image_upload" class="fileUpload"/>
            <button type="button" id="btn-remove-img" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" disabled>
              X
            </button>
            <a id="too-large"></a>
          </div>

          <iframe id="upload_target" name="upload_target" src="#" style="width:0;height:0;border:0px solid #fff;" hidden></iframe>   
        </form>

        <a id="dialog"></a>

        <button id="confirm-button" type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
          Confirm
        </button>
        <br>
        <button id="btn-back" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
          Back
        </button>

        <div id="valid" hidden></div>
        <div id="is-good-image" hidden></div>
      </div>

    </div>

  <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="
    <?php
      echo '//'.$_SERVER['HTTP_HOST'].'/internship/error.js';
    ?>
  "></script>
  <script src="
    <?php
      echo '//'.$_SERVER['HTTP_HOST'].'/internship/size-check.js';
    ?>
  "></script>
  <script>
    if (inComputerSize()) {
      $("#regis-form").children(".mdl-textfield").addClass('mdl-textfield--floating-label');
    } else {
      $("#regis-form").children(".mdl-textfield").removeClass('mdl-textfield--floating-label');
    }

    $(document).ready(function(){
      $('#is-good-image').val('true');

      $('#image_upload').change(function() {
        if ($('#image_upload')[0].files.length === 0) {//Deselected
          $("#too-large").html("");
          $('#is-good-image').val('true');
          $('#confirm-button').prop('disabled', false);
          $('#btn-remove-img').prop('disabled', true);
        } else {
          if (window.File && window.FileReader && window.FileList && window.Blob)
          {
            //get the file size and file type from file input field
            var file = $('#image_upload')[0].files[0];
            var fsize = file.size;
      
            if(fsize > 1048576) //do something if file size more than 1 mb (1048576)
              {
                $("#too-large").html("<br>File is too large! Must be 1 MB or smaller.<br>");
                $('#is-good-image').val('false');
                $('#confirm-button').prop('disabled', true);
              } else  {
                $("#too-large").html("");
                $('#is-good-image').val('true');
                $('#confirm-button').prop('disabled', false);
              }
          } else {
            $("#too-large").html("<br>Please upgrade your browser, because your current browser lacks some new features we need!<br>");
          }
          $('#btn-remove-img').prop('disabled', false);
        }
      });

      $("#btn-remove-img").click(function() {
        $('#image_upload').val('');
        $('#btn-remove-img').prop('disabled', true);
        $("#too-large").html("");
        $('#is-good-image').val('true');
        $('#confirm-button').prop('disabled', false);
      });

      $(".mdl-textfield__input").keyup(function (){
        $(this).prop('required', false);
        $(this).parent().removeClass('is-invalid');
      });

      $(".mdl-button[type='submit']").click(function (event){
        var required_fields = {
          user_name: 0,
          password: 1,
          password_confirm: 2,
          email: 3
        }
        var valid = true;
        var email_format = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
        if($("#user_name").val() === "") {
          $("#regis-form").children(".required").eq(required_fields.user_name).addClass('is-invalid');
          $("#regis-form").children(".required").eq(required_fields.user_name).prop('required', true);
          valid = false;
        }
        if($("#password").val() === "") {
          $("#regis-form").children(".required").eq(required_fields.password).addClass('is-invalid');
          $("#regis-form").children(".required").eq(required_fields.password).prop('required', true);
          valid = false;
        }
        if($("#password_confirm").val() === "") {
          $("#regis-form").children(".required").eq(required_fields.password_confirm).addClass('is-invalid');
          $("#regis-form").children(".required").eq(required_fields.password_confirm).prop('required', true);
          valid = false;
        };
        if($("#email").val() === "" || !email_format.test($("#email").val())) {
          $("#regis-form").children(".required").eq(required_fields.email).addClass('is-invalid');
          $("#regis-form").children(".required").eq(required_fields.email).prop('required', true);
          valid = false;
        }

        //Call this if all are valid
        if (valid) {
          $('#regis-form').trigger('submit');
        }
      });

      $('#regis-form').submit(function(evt) {
        evt.preventDefault();

        var formData = new FormData(this);

        $.ajax({
        type: 'POST',
        url: '//'+window.location.hostname+'/internship/login.php/register',
        data: formData,
        cache: false,
        contentType: false,
        processData: false,
        success: function(data) {
          window.location.href = '//'+window.location.hostname+'/internship/login.php/register-success';
        },
        error: onError
        });
      });

      $("#btn-back").click(function() {
        window.location.href = '//'+window.location.hostname+'/internship/login.php';
      });
    });
    </script>
  </body>
</html>
