<?php
$session = new \SlimSession\Helper;
?>

<html>
  <head>
    <title>WebIntern - Want to join us?</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" type="text/css" href="//localhost/internship/front-pages.css">
  </head>

  <body>
    <div class="main">
      <h3 class="header">Want to join us?</h3>

      <form class="form" id="regis-form" enctype="multipart/form-data" target="upload_target">
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <input class="mdl-textfield__input" type="text" id="user_name" name="user_name">
          <label class="mdl-textfield__label" for="user_name">Username (Your unique identity)</label>
        </div>

        <br><br>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <input class="mdl-textfield__input" type="password" id="password" name="password">
          <label class="mdl-textfield__label" for="password">Password (Your security key)</label>
        </div>
      
        <br><br>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <input class="mdl-textfield__input" type="password" id="password_confirm" name="password_confirm">
          <label class="mdl-textfield__label" for="password_confirm">Confirm Password (Make sure you can keep this key)</label>
        </div>
      
        <br><br>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <input class="mdl-textfield__input" type="text" id="email" name="email">
          <label class="mdl-textfield__label" for="email">Email (Your unique contact source)</label>
        </div>
      
        <br><br>

        <div>
          <b>Profile Image : </b>
          <input type="file" accept="image/*" id="image_upload" name="image_upload" class="fileUpload"/>
          <a id="too-large"></a>
        </div>

        <iframe id="upload_target" name="upload_target" src="#" style="width:0;height:0;border:0px solid #fff;" hidden></iframe>   
      </form>

      <a id="dialog"></a>

      <button id="confirm-button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
        Confirm
      </button>
      <br>
      <button id="btn-back" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
        Back
      </button>

      <div id="valid" hidden></div>
      <div id="is-good-image" hidden></div>
    </div>

  <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="//localhost/internship/error.js"></script>
  <script>$("#elementId").attr("required", "true");
    $(document).ready(function(){
      $('#valid').val('false');
      $('#is-good-image').val('true');
      $('#confirm-button').prop('disabled', true);

      $('#regis-form').find('input').each(function() {
        $(this).keyup(function() {
          if ()
          {
            $('#valid').val('false');
            $('#confirm-button').prop('disabled', true);
          } //|| $('#password').val() !== $('#password_confirm').val())  before we add this, we need to able to tell the user directly of the password status below password confirm
          else
          {
            $('#valid').val('true');
            if ($('#is-good-image').val() === 'true') {
              $('#confirm-button').prop('disabled', false);
            }
          }
        });
      });

      $('#image_upload').change(function() {
        if ($('#image_upload')[0].files.length === 0) {//Deselected
          $("#too-large").html("");
          $('#is-good-image').val('true');
          if ($('#valid').val() === 'true') {
            $('#confirm-button').prop('disabled', false);
          }
        } else {
          if (window.File && window.FileReader && window.FileList && window.Blob)
          {
            //get the file size and file type from file input field
            var file = $('#image_upload')[0].files[0];
            var fsize = file.size;
      
            if(fsize > 1048576) //do something if file size more than 1 mb (1048576)
              {
                //alert(fsize +" bytes\nToo big!");
                $("#too-large").html("<br>File is too large! Must be 1 MB or smaller.<br>");
                $('#is-good-image').val('false');
                $('#confirm-button').prop('disabled', true);
              } else  {
                //alert(fsize +" bytes\nYou are good to go!");
                $("#too-large").html("");
                $('#is-good-image').val('true');
                if ($('#valid').val() === 'true') {
                  $('#confirm-button').prop('disabled', false);
                }
              }
          } else {
            $("#too-large").html("<br>Please upgrade your browser, because your current browser lacks some new features we need!<br>");
          }
        }
      });

      $("#confirm-button").click(function() {
        $('#regis-form').trigger('submit');
      });

      $('#regis-form').submit(function(evt) {
        evt.preventDefault();

        var formData = new FormData(this);

        $.ajax({
        type: 'POST',
        url: '//localhost/internship/login.php/register',
        data: formData,
        cache: false,
        contentType: false,
        processData: false,
        success: function(data) {
          window.location.href = '//localhost/internship/login.php/register-success';
        },
        error: onError
        });
      });

      $("#btn-back").click(function() {
        window.location.href = '//localhost/internship/login.php';
      });
    });

    function validateEmail(emailField) {
        var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
        if (reg.test(emailField.value) == false) 
        {
            return false;
        }
        return true;
    }
    </script>
  </body>
</html>
