<?php
$session = new \SlimSession\Helper;
?>

<html>
  <head>
    <title>WebIntern - Sign up Success!!</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <link rel="stylesheet" type="text/css" href="
    <?php
      echo '//'.$_SERVER['HTTP_HOST'].'/internship/front-pages.css';
    ?>
    ">
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">WebIntern</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation mdl-layout--large-screen-only">
            <a class="mdl-navigation__link" href="
            <?php
              echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php';
            ?>
            ">Sign in</a>
            <a class="mdl-navigation__link" href="
            <?php
              echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php/regis';
            ?>
            ">Join us</a>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title-drawer">WebIntern</span>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" href="
          <?php
            echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php';
          ?>
          ">Sign in</a>
          <a class="mdl-navigation__link" href="
          <?php
            echo '//'.$_SERVER['HTTP_HOST'].'/internship/login.php/regis';
          ?>
          ">Join us</a>
        </nav>
      </div>
      <div class="main">
        <h3 class="header">Sign up Success!!</h3>

        <h6 class="msg">Thank you for joining us! Let's try to sign in.</h6>

        <button id="back-btn" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
          Back to sign in page
        </button>
      </div>

    </div>

    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
      $(document).ready(function(){
        $("#back-btn").click(function() {
          window.location.href = '//'+window.location.hostname+'/internship/login.php';
        });
      });
    </script>
  </body>
</html>
